language: python

# Old:
# install:
#  - pip install .

# Miniconda-based setup of the Scipy stack Based on
# https://gist.github.com/dan-blanchard/7045057.

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  ##- conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  ##- conda install --yes -n condaenv pip
  ##- source activate condaenv
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  # - sudo rm -rf /dev/shm
  # - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy
  - python setup.py install

script: python mp_inference.py poolK1_chr12.txt -n 100 -np

sudo: false
